name: "Backup Repository"
description: "Backup a repository using user:token auth."
branding:
  icon: "archive"
  color: "blue"
inputs:
  bitbucket_app_user:
    description: Bitbucket app username
    required: true
  bitbucket_app_password:
    description: Bitbucket app password
    required: true
  target_repo:
    description: "Target repo (owner/repo)"
    required: true
runs:
  using: 'docker'
  image: 'dockerfile'
